name: Nightly Retrain
on:
  schedule:
    - cron: "5 2 * * *"
  workflow_dispatch: {}
jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { persist-credentials: true }
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-train.txt
      - name: Retrain pipeline
        run: python -m app.retrain
      - name: Commit artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add models/* data/*.csv 2>/dev/null || true
          git commit -m "nightly: retrain & update models/data" || echo "No changes"
          git push
